# Feature Engineering

### whats feature engineering - enriching our dataset with extra informations thats likely going to help our models

In [13]:
# using pandas
#Read the dataset from a CSV file

import pandas as pd
import boto3

In [5]:
#loading the dataset and reading the CSV files
df = pd.read_csv("C:/Users/PRINCES/Documents/GitHub/Churn-Prediction-Pipeline/data/raw/Telco-Customer-Churn.csv")

In [6]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
# Monthly charge -- Average monthly charge a customer pays

df['MonthlyCharges_Average'] = df['MonthlyCharges'].astype(float).mean()

In [8]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,MonthlyCharges_Average
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,64.761692
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.5,No,64.761692
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,64.761692
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,64.761692
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,64.761692

In [9]:
# convert Yes/No to 1/0 for some services

df["HasPhoneService"] = df["PhoneService"].apply(lambda x: 1 if x == "Yes" else 0)
df['IsSeniorCitizen'] = df['SeniorCitizen'].apply(lambda x: 1 if x == 1 else 0)
df['HasPartner'] = df['Partner'].apply(lambda x: 1 if x == "Yes" else 0)
df['HasDependents'] = df['Dependents'].apply(lambda x: 1 if x == "Yes" else 0)
df['HasSecurity'] = df['OnlineSecurity'].apply(lambda x: 1 if x == "Yes" else 0)

In [10]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,PaymentMethod,MonthlyCharges,TotalCharges,Churn,MonthlyCharges_Average,HasPhoneService,IsSeniorCitizen,HasPartner,HasDependents,HasSecurity
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,Electronic check,29.85,29.85,No,64.761692,0,0,1,0,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Mailed check,56.95,1889.5,No,64.761692,1,0,0,0,1
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,Mailed check,53.85,108.15,Yes,64.761692,1,0,0,0,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Bank transfer (automatic),42.30,1840.75,No,64.761692,0,0,0,0,1
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Electronic check,70.70,151.65,Yes,64.761692,1,0,0,0,0

# Save to S3

In [11]:
# save the processed data to a new CSV file
filename = "telco_churn_processed.csv"
df.to_csv(filename, index=False)

print(f"Processed data saved to {filename}")

Processed data saved to telco_churn_processed.csv

In [14]:
# upload the processed file to s3 bucket

# step 1- create s3 client
s3_client = boto3.client('s3')
bucket_name = "pr-churn-bucket"

# step 2 - upload the file
s3_client.upload_file(
    filename,
    bucket_name,
    'telco_churn_processed.csv'
)

print(f"Processed file uploaded to s3://{bucket_name}/telco_churn_processed.csv successfully")

Processed file uploaded to s3://pr-churn-bucket/telco_churn_processed.csv successfully